name: Windows-CI

on: [push]

jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin]
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Install cUrl
        run: choco install curl
      - name: Install sudo
        run: choco install sudo
      - name: Install Roswell
        shell: bash
        env:
          LISP: ${{ matrix.lisp }}
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
      - name: Install Rove
        shell: bash
        run: ros install rove
      - name: Run tests
        shell: bash
        run: |
          PATH="~/.roswell/bin:$PATH"
          rove rayden.asd
